# Introduction to NumPy and PyTorch

Video: https://imperial.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=61ec89fb-6db3-494d-bbd3-b079011c4109

Numpy is a widely used Python library for scientific computing with
multidimensional arrays.

PyTorch is a popular library used for Deep Learning research and applications. It is similar to numpy in that it is built around the manipulation of multidimensional arrays, but with a few additional features:
* GPU support
* Automatic differentiation
* Other utilities to facilitate building and training neural network

This notebook contains examples some of the essential features of NumPy and PyTorch. Examples from each framework will be presented side-by-side to highlight the similarities (and occasional differences) between their APIs.

In particular, we will first explore some of the core operations involving the central data structures in each library, the NumPy `ndarray` and the PyTorch `Tensor`.

Finally, we will look at the basics of automatic differentiation in PyTorch.

The official documentation is a good place to learn more:
* https://docs.scipy.org/doc/numpy/user/index.html
* https://pytorch.org/docs/stable/index.html
* https://pytorch.org/tutorials/

To start, it is typically a good idea to set a random seed to facilitate reproducibility of experiments. So we first import our libraries and set the random seed in both:

In [6]:
import numpy as np
import torch as torch

np.random.seed(0)
torch.manual_seed(0)

use_cuda = torch.cuda.is_available()
device = torch.device('cuda' if use_cuda else 'cpu')
use_cuda, device

(True, device(type='cuda'))

### Creating arrays

We can create arrays from lists of values, or alternatively use a number of helper functions to create specific types of arrays. In the latter case, we typically pass in the desired size of the array as the first argument (see examples below - should be fairly self-explanatory).

##### From list

In [3]:
a = np.array([1, 2, 3]) # in numpy
a

array([1, 2, 3])

In [7]:
a_ = torch.Tensor([1, 2, 3]) # in pytorch equivalently
a_

tensor([1., 2., 3.])

In [8]:
a_long = torch.LongTensor([1, 2, 3]) # explicitly construct an integer array
a_long

tensor([1, 2, 3])

#### Empty array

In [11]:
b = np.empty((3, 2)) # 3 x 2 array
b

array([[4.66006948e-310, 0.00000000e+000],
       [2.84809454e-306, 4.66108410e-310],
       [5.30498948e-315, 6.91097160e-310]])

In [13]:
b_ = torch.empty((3, 2))
b_

tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00]])

#### Zeroes

In [14]:
c = np.zeros((2, 3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
c_ = torch.zeros((2, 3))
c_

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### Ones

In [16]:
d = np.ones(3)
d

array([1., 1., 1.])

In [17]:
d_ = torch.ones(3)
d_

tensor([1., 1., 1.])

#### Samples from Uniform[0, 1]

In [18]:
e = np.random.random((2, 3))
e

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [19]:
e_ = torch.rand((2, 3))
e_

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

### Basic properties of arrays

#### Shape

Shape: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

shape seems to be in vector-wise notation, so we begin with a vector, i.e. we go up to down to index it. This has a shape of (n,) because it is so far a 1-dimensional array. Once we add a second dimension, like (n,1) the array may look the same but it is constructed differently, e.g. `[1,2,3].shape => (3,)` but `[[1,2,3]].shape => (3,)` 

In [20]:
print(b)
b.shape

[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]
 [5.30498948e-315 6.91097160e-310]]


(3, 2)

In [21]:
print(b_)
b_.shape

tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00]])


torch.Size([3, 2])

#### dtype

What data-type it is

In [22]:
print(a.dtype)
print(e.dtype)

int64
float64


In [24]:
print(a_.dtype)
print(a_long.dtype)
print(e_.dtype)

torch.float32
torch.int64
torch.float32


### Indexing

#### Integer indexing

In [27]:
print(b)
print('---')
print(b[0])
print('---')
print(b[0, 0])

[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]
 [5.30498948e-315 6.91097160e-310]]
---
[4.66006948e-310 0.00000000e+000]
---
4.6600694849782e-310


In [28]:
print(b_)
print('---')
print(b_[0])
print('---')
print(b_[1])
print('---')
print(b_[0, 0])

tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00]])
---
tensor([-1.0101e-25,  3.0780e-41])
---
tensor([-9.6388e-26,  3.0780e-41])
---
tensor(-1.0101e-25)


#### Slicing

In [29]:
print(b)
print()
print(b[:2])
print(b[2:])
print(b[1:3])
print(b[:, :1]) # give me all elements along the first axis, give me all elements up to but not including index 1, i.e. all items of the first column.
print(b[:2, :2])

[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]
 [5.30498948e-315 6.91097160e-310]]

[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]]
[[5.30498948e-315 6.91097160e-310]]
[[2.84809454e-306 4.66108410e-310]
 [5.30498948e-315 6.91097160e-310]]
[[4.66006948e-310]
 [2.84809454e-306]
 [5.30498948e-315]]
[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]]


In [30]:
print(b_[:2])
print(b_[1:3])
print(b_[:, :1])
print(b_[:2, :2])

tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41]])
tensor([[-9.6388e-26,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00]])
tensor([[-1.0101e-25],
        [-9.6388e-26],
        [ 0.0000e+00]])
tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41]])


#### Boolean indexing

In [31]:
print(a)
print()
idx = a >= 2
print(idx)
print(a[idx])

[1 2 3]

[False  True  True]
[2 3]


In [32]:
idx_ = a_ >= 2
print(idx_)
print(a_[idx_])

tensor([False,  True,  True])
tensor([2., 3.])


### Mathematical operations

#### Sum

In [33]:
print(e)
print()
print(e.sum())
print(np.sum(e))
print(e.sum(axis=0)) # numpy uses axis
print(e.sum(axis=1))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

3.481198341773846
3.481198341773846
[1.09369669 1.13884417 1.24865749]
[1.86676625 1.6144321 ]


In [34]:
print(e_)
print()
print(e_.sum())
print(torch.sum(e_))
print(e_.sum(dim=0)) # pytorch uses dim
print(e_.sum(dim=1))

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

tensor(2.4265)
tensor(2.4265)
tensor([0.6283, 1.0756, 0.7226])
tensor([1.3530, 1.0735])


#### Elementwise sum

In [35]:
print(a)
print(d)
print()
print(a + d)

[1 2 3]
[1. 1. 1.]

[2. 3. 4.]


In [36]:
print(a_)
print(d_)
print()
print(a_ + d_)

tensor([1., 2., 3.])
tensor([1., 1., 1.])

tensor([2., 3., 4.])


#### Elementwise multiplication

In [38]:
print(a)
print(d)
print()
print(a * d)

[1 2 3]
[1. 1. 1.]

[1. 2. 3.]


In [39]:
print(a_)
print(d_)
print()
print(a_ * d_)

tensor([1., 2., 3.])
tensor([1., 1., 1.])

tensor([1., 2., 3.])


#### Dot product

In [37]:
print(a)
print(d)
print()
print(np.dot(a, d))
print(a.dot(d))

[1 2 3]
[1. 1. 1.]

6.0
6.0


In [40]:
print(a_)
print(d_)
print()
print(torch.dot(a_, d_))
print(a_.dot(d_))

tensor([1., 2., 3.])
tensor([1., 1., 1.])

tensor(6.)
tensor(6.)


#### Matrix multiplication

In [41]:
print(a)
print(b)
print()
print(np.matmul(a, b))
print(a @ b)

[1 2 3]
[[4.66006948e-310 0.00000000e+000]
 [2.84809454e-306 4.66108410e-310]
 [5.30498948e-315 6.91097160e-310]]

[5.6966551e-306 3.0055083e-309]
[5.6966551e-306 3.0055083e-309]


In [42]:
print(a_)
print(b_)
print()
print(torch.matmul(a_, b_))
print(a_ @ b_)

tensor([1., 2., 3.])
tensor([[-1.0101e-25,  3.0780e-41],
        [-9.6388e-26,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00]])

tensor([-2.9379e-25,  9.2339e-41])
tensor([-2.9379e-25,  9.2339e-41])


### Broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting

Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

Rules:

- they are equal, or
- one of them is 1.

```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```

both the A and B arrays have axes with length one that are expanded to a larger size during the broadcast operation:


#### Compatible shapes

In [43]:
f = torch.rand((2, 1, 3))
g = torch.ones((3, 3))
print(f)
print(g)

tensor([[[0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [44]:
print(f)
print(g)
print(f.shape)
print(g.shape)
print()
print(f + g)
print(f * g)

print((f + g).shape)
print((f * g).shape)

tensor([[[0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 1, 3])
torch.Size([3, 3])

tensor([[[1.4901, 1.8964, 1.4556],
         [1.4901, 1.8964, 1.4556],
         [1.4901, 1.8964, 1.4556]],

        [[1.6323, 1.3489, 1.4017],
         [1.6323, 1.3489, 1.4017],
         [1.6323, 1.3489, 1.4017]]])
tensor([[[0.4901, 0.8964, 0.4556],
         [0.4901, 0.8964, 0.4556],
         [0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017],
         [0.6323, 0.3489, 0.4017],
         [0.6323, 0.3489, 0.4017]]])
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])


#### Incompatible shapes

In [45]:
h = np.random.random((2, 3))
i = np.random.random((2, 2))
print(h.shape)
print(i.shape)

# Raises error
h + i

(2, 3)
(2, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### Converting between NumPy and PyTorch

In [46]:
arr_np = np.random.random((5, 5))
arr_th = torch.rand((5, 5))

# From numpy
torch.Tensor(arr_np)
print(torch.from_numpy(arr_np))

# To numpy
print()
print(arr_th.numpy())


tensor([[0.0202, 0.8326, 0.7782, 0.8700, 0.9786],
        [0.7992, 0.4615, 0.7805, 0.1183, 0.6399],
        [0.1434, 0.9447, 0.5218, 0.4147, 0.2646],
        [0.7742, 0.4562, 0.5684, 0.0188, 0.6176],
        [0.6121, 0.6169, 0.9437, 0.6818, 0.3595]], dtype=torch.float64)

[[0.02232575 0.16885895 0.29388845 0.5185218  0.6976676 ]
 [0.8000114  0.16102946 0.28226858 0.68160856 0.915194  ]
 [0.3970999  0.8741559  0.41940832 0.55290705 0.9527381 ]
 [0.03616482 0.18523103 0.37341738 0.30510002 0.9320004 ]
 [0.17591017 0.26983356 0.15067977 0.03171951 0.20812976]]


### Autograd basics

https://pytorch.org/docs/stable/autograd.html#module-torch.autograd

provides classes and functions implementing automatic differentiation of arbitrary scalar valued functions

- `backward` Computes the sum of gradients of given tensors with respect to graph leaves.
- `grad` Computes and returns the sum of gradients of outputs with respect to the inputs.

In [53]:
W = torch.randn((7, 5), requires_grad=True) # flag indicates that we are interested in taking the gradient of something with respect to this matrix
x = torch.randn(5)
y = torch.matmul(W, x)
z = y.sum()
print(W)
print(x)
print(z)

tensor([[-0.5918,  0.1508, -1.0411, -0.7205, -2.2148],
        [-0.6837,  0.5164,  0.5588,  0.0832,  0.4228],
        [-1.8687, -1.1057,  0.1437,  0.5836,  1.3482],
        [-0.8137,  0.3609, -1.3533, -0.2071,  0.4201],
        [ 1.1290,  0.4264, -1.1361, -0.1292, -0.0546],
        [ 0.4083,  1.1264, -0.6079, -0.3625, -1.5072],
        [-0.5087, -1.2426,  1.2846,  0.2438,  0.5304]], requires_grad=True)
tensor([ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091])
tensor(-5.4794, grad_fn=<SumBackward0>)


In [54]:
z.backward() # suppose z is the loss function. 

In [55]:
W.grad

tensor([[ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091],
        [ 0.7308, -0.0440,  1.1634,  0.1520,  0.7091]])

In [56]:
x.grad is None # didn't set the flag

True

In [57]:
# Another example involving differentiating through a for-loop
W = torch.randn((5, 5), requires_grad=True)
x = torch.randn(5)
for i in range(3):
    x = torch.matmul(W, x)
z = x.sum()
z.backward()
print(W.grad)

tensor([[-3.0717, -3.9963,  2.0815, -3.6594, -0.5872],
        [-4.6441, -7.1057,  2.6748, -4.7311,  0.0932],
        [ 1.3500, -5.7245, -3.9111, -0.2535, -3.3786],
        [ 0.8487,  0.8296, -0.6063, -0.8777, -2.5289],
        [ 4.1824,  4.8271, -2.9358,  1.4917, -4.1890]])
